## 2. Feature Engineering Review

This notebook reviews feature datasets already produced by the project. It does not regenerate features or change any files.

The available datasets may differ as the pipeline evolves, so the notebook checks which files exist before inspecting them.

In [1]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd()
if not (BASE_DIR / "data").exists():
    BASE_DIR = BASE_DIR.parent

PROCESSED = BASE_DIR / "data" / "processed"
CANDIDATES = [
    "customer_features.csv",
    "customer_churn_features.csv",
    "behavior_features.csv",
    "advanced_customer_features.csv",
    "clv_regression_data.csv",
    "ml_ready_data.csv",
    "tableau_customer_data.csv",
]

available = [PROCESSED / name for name in CANDIDATES
             if (PROCESSED / name).exists()]

print("Project:", BASE_DIR)
display(pd.DataFrame({
    "file": [p.name for p in available],
    "size_MB": [round(p.stat().st_size / (1024 * 1024), 2) for p in available]
}))

Project: c:\Users\RITUL\OneDrive\Desktop\AI Projects\customer-behavior-prediction

                             file  size_MB
0           customer_features.csv     0.79
1     customer_churn_features.csv     0.15
2           behavior_features.csv     0.20
3  advanced_customer_features.csv     0.37
4         clv_regression_data.csv     0.93
5               ml_ready_data.csv     1.50
6       tableau_customer_data.csv     1.12

In [2]:
# Inspect each available dataset using a bounded sample.
feature_samples = {}

for path in available:
    sample = pd.read_csv(path, nrows=10_000, low_memory=False)
    feature_samples[path.name] = sample
    print(f"\n{path.name}: sample shape = {sample.shape}")
    display(sample.head(3))
    print("Missing values in sample:", int(sample.isna().sum().sum()))
    print("Duplicate rows in sample:", int(sample.duplicated().sum()))

customer_features.csv: sample shape = (5939, 18)

,Customer_ID,Recency,Frequency,Monetary,Total_Quantity,Average_Order_Value,First_Purchase_Date,Last_Purchase_Date,Customer_Lifetime_Days,Average_Basket_Size,Recency_Score,Frequency_Score,Monetary_Score,RFM_Score,CLV,Unique_Products,Unique_Countries,Purchase_Frequency_Per_Month
0,12346.0,325,17,-51.74,53,-1.100851,2009-12-14 08:34:00,2011-01-18 10:17:00,400,3.117647,2,5,1,8,-0.129350,30,1,1.275000
1,12347.0,1,8,4921.53,2967,22.169054,2010-10-31 14:20:00,2011-12-07 15:52:00,402,370.875000,5,4,5,14,12.242612,126,1,0.597015
2,12348.0,74,5,2019.40,2714,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,542.800000,3,3,4,10,5.578453,25,1,0.414365

Missing values in sample: 0
Duplicate rows in sample: 0

customer_churn_features.csv: sample shape = (5344, 6)

   Customer_ID  Recency  Frequency  Monetary  Total_Quantity  Churn
0      12346.0      235         17    -51.74              53      1
1      12347.0       39          6   3402.39            2099      0
2      12348.0      158          4   1709.40            2497      0

Missing values in sample: 0
Duplicate rows in sample: 0

behavior_features.csv: sample shape = (5346, 3)

   Customer_ID  Return_Rate  Price_Sensitivity_Proxy
0      12346.0     0.291667                 0.140845
1      12347.0     0.000000                 0.276651
2      12348.0     0.000000                 0.241692

Missing values in sample: 0
Duplicate rows in sample: 0

advanced_customer_features.csv: sample shape = (5281, 6)

,Customer_ID,Purchase_Frequency_Trend,Purchase_Gap_Variance,Seasonal_Purchase_Concentration,Product_Category_Affinity,Engagement_Score
0,12346.0,0.837209,4280.690909,0.416667,0.5625,0.070954
1,12347.0,0.592105,162.800000,0.166667,0.2500,0.017289
2,12348.0,0.547945,457.000000,0.250000,0.5000,0.007659

Missing values in sample: 0
Duplicate rows in sample: 0

clv_regression_data.csv: sample shape = (5281, 19)

,Customer_ID,Recency,Frequency,Monetary,Average_Order_Value,Total_Quantity,Unique_Products,Customer_Lifetime_Days,CLV,Purchase_Frequency_Per_Month,Average_Basket_Size,Purchase_Frequency_Trend,Purchase_Gap_Variance,Seasonal_Purchase_Concentration,Product_Category_Affinity,Engagement_Score,Return_Rate,Price_Sensitivity_Proxy,Future_90D_CLV
0,12346.0,235,12,77556.46,2281.072353,74285,27,400,193.891150,0.900000,6190.416667,0.837209,4280.690909,0.416667,0.5625,0.070954,0.291667,0.140845,0.00
1,12347.0,39,6,3402.39,20.746280,2099,107,274,12.417482,0.656934,349.833333,0.592105,162.800000,0.166667,0.2500,0.017289,0.000000,0.276651,1519.14
2,12348.0,158,4,1709.40,35.612500,2497,25,189,9.044444,0.634921,624.250000,0.547945,457.000000,0.250000,0.5000,0.007659,0.000000,0.241692,310.00

Missing values in sample: 0
Duplicate rows in sample: 0

ml_ready_data.csv: sample shape = (5281, 66)

,Customer_ID,Recency,Frequency,Monetary,Total_Quantity,Average_Order_Value,Customer_Lifetime_Days,Average_Basket_Size,Recency_Score,Frequency_Score,...,Country_Spain,Country_Sweden,Country_Switzerland,Country_Thailand,Country_USA,Country_United Arab Emirates,Country_United Kingdom,Country_Unspecified,Country_West Indies,StockCode_Frequency
0,12346.0,235,12,77556.46,74285,2281.072353,400,2184.852941,3,5,...,0,0,0,0,0,0,1,0,0,0.000613
1,12347.0,39,6,3402.39,2099,20.746280,274,12.798780,4,4,...,0,0,0,0,0,0,0,0,0,0.000688
2,12348.0,158,4,1709.40,2497,35.612500,189,52.020833,3,3,...,0,0,0,0,0,0,0,0,0,0.001050

Missing values in sample: 0
Duplicate rows in sample: 0

tableau_customer_data.csv: sample shape = (5281, 27)

,Customer_ID,Recency,Frequency,Monetary,Total_Quantity,Average_Order_Value,Customer_Lifetime_Days,Average_Basket_Size,Recency_Score,Frequency_Score,...,Purchase_Frequency_Trend,Purchase_Gap_Variance,Seasonal_Purchase_Concentration,Product_Category_Affinity,Engagement_Score,Return_Rate,Price_Sensitivity_Proxy,Churn_Probability,Risk_Level,Segment
0,12346,235,12,77556.46,74285,2281.072353,400,2184.852941,3,5,...,0.837209,4280.690909,0.416667,0.5625,0.070954,0.291667,0.140845,0.494398,Borderline,3
1,12347,39,6,3402.39,2099,20.746280,274,12.798780,4,4,...,0.592105,162.800000,0.166667,0.2500,0.017289,0.000000,0.276651,0.100193,Low,0
2,12348,158,4,1709.40,2497,35.612500,189,52.020833,3,3,...,0.547945,457.000000,0.250000,0.5000,0.007659,0.000000,0.241692,0.440854,Borderline,1

Missing values in sample: 0
Duplicate rows in sample: 0

In [3]:
# Review columns and likely target fields.
for filename, sample in feature_samples.items():
    print(f"\n{filename}")
    display(pd.DataFrame({
        "column": sample.columns,
        "dtype": sample.dtypes.astype(str).values,
        "missing_in_sample": sample.isna().sum().values,
        "unique_in_sample": sample.nunique(dropna=False).values,
    }))
    targets = [c for c in sample.columns
               if c.lower() in {"churn", "clv", "customer_id", "target"}]
    if targets:
        print("Potential target/identifier columns:", targets)
        for col in targets:
            if sample[col].nunique(dropna=False) <= 20:
                display(sample[col].value_counts(dropna=False).to_frame("count"))

customer_features.csv

                          column    dtype  missing_in_sample  unique_in_sample
0                    Customer_ID  float64                  0              5939
1                        Recency    int64                  0               672
2                      Frequency    int64                  0               102
3                       Monetary  float64                  0              5826
4                 Total_Quantity    int64                  0              2372
5            Average_Order_Value  float64                  0              5872
6            First_Purchase_Date   object                  0              5808
7             Last_Purchase_Date   object                  0              5793
8         Customer_Lifetime_Days    int64                  0               732
9            Average_Basket_Size  float64                  0              3190
10                 Recency_Score    int64                  0                 5
11               Frequency_Score    int64                  0                 5
12                Monetary_Score    int64                  0                 5
13                     RFM_Score    int64                  0                13
14                           CLV  float64                  0              5875
15               Unique_Products    int64                  0               467
16              Unique_Countries    int64                  0                 2
17  Purchase_Frequency_Per_Month  float64                  0              2503

Potential target/identifier columns: ['Customer_ID', 'CLV']

customer_churn_features.csv

           column    dtype  missing_in_sample  unique_in_sample
0     Customer_ID  float64                  0              5344
1         Recency    int64                  0               592
2       Frequency    int64                  0                90
3        Monetary  float64                  0              5240
4  Total_Quantity    int64                  0              2142
5           Churn    int64                  0                 2

Potential target/identifier columns: ['Customer_ID', 'Churn']

       count
Churn
1       3022
0       2322

behavior_features.csv

                    column    dtype  missing_in_sample  unique_in_sample
0              Customer_ID  float64                  0              5346
1              Return_Rate  float64                  0              1108
2  Price_Sensitivity_Proxy  float64                  0              5089

Potential target/identifier columns: ['Customer_ID']

advanced_customer_features.csv

,column,dtype,missing_in_sample,unique_in_sample
0,Customer_ID,float64,0,5281
1,Purchase_Frequency_Trend,float64,0,2003
2,Purchase_Gap_Variance,float64,0,2469
3,Seasonal_Purchase_Concentration,float64,0,134
4,Product_Category_Affinity,float64,0,520
5,Engagement_Score,float64,0,5280

Potential target/identifier columns: ['Customer_ID']

clv_regression_data.csv

,column,dtype,missing_in_sample,unique_in_sample
0,Customer_ID,float64,0,5281
1,Recency,int64,0,594
2,Frequency,int64,0,83
3,Monetary,float64,0,5174
4,Average_Order_Value,float64,0,5218
5,Total_Quantity,int64,0,2153
6,Unique_Products,int64,0,415
7,Customer_Lifetime_Days,int64,0,642
8,CLV,float64,0,5219
9,Purchase_Frequency_Per_Month,float64,0,1937
10,Average_Basket_Size,float64,0,2695
11,Purchase_Frequency_Trend,float64,0,2003
12,Purchase_Gap_Variance,float64,0,2469
13,Seasonal_Purchase_Concentration,float64,0,134
14,Product_Category_Affinity,float64,0,520
15,Engagement_Score,float64,0,5280
16,Return_Rate,float64,0,1107
17,Price_Sensitivity_Proxy,float64,0,5087
18,Future_90D_CLV,float64,0,2268

Potential target/identifier columns: ['Customer_ID', 'CLV']

ml_ready_data.csv

                          column    dtype  missing_in_sample  unique_in_sample
0                    Customer_ID  float64                  0              5281
1                        Recency    int64                  0               594
2                      Frequency    int64                  0                83
3                       Monetary  float64                  0              5174
4                 Total_Quantity    int64                  0              2153
..                           ...      ...                ...               ...
61  Country_United Arab Emirates    int64                  0                 2
62        Country_United Kingdom    int64                  0                 2
63           Country_Unspecified    int64                  0                 2
64           Country_West Indies    int64                  0                 2
65           StockCode_Frequency  float64                  0              5158

[66 rows x 4 columns]

Potential target/identifier columns: ['Customer_ID', 'CLV', 'Churn']

       count
Churn
1       2989
0       2292

tableau_customer_data.csv

,column,dtype,missing_in_sample,unique_in_sample
0,Customer_ID,int64,0,5281
1,Recency,int64,0,594
2,Frequency,int64,0,83
3,Monetary,float64,0,5174
4,Total_Quantity,int64,0,2153
5,Average_Order_Value,float64,0,5218
6,Customer_Lifetime_Days,int64,0,642
7,Average_Basket_Size,float64,0,4305
8,Recency_Score,int64,0,5
9,Frequency_Score,int64,0,5
10,Monetary_Score,int64,0,5
11,RFM_Score,int64,0,13
12,CLV,float64,0,5219
13,Unique_Products,int64,0,415
14,Unique_Countries,int64,0,2
15,Purchase_Frequency_Per_Month,float64,0,1937
16,Churn,int64,0,2
17,Purchase_Frequency_Trend,float64,0,2003
18,Purchase_Gap_Variance,float64,0,2469
19,Seasonal_Purchase_Concentration,float64,0,134
20,Product_Category_Affinity,float64,0,520
21,Engagement_Score,float64,0,5280
22,Return_Rate,float64,0,1107
23,Price_Sensitivity_Proxy,float64,0,5087
24,Churn_Probability,float64,0,5281
25,Risk_Level,object,0,3
26,Segment,int64,0,5

Potential target/identifier columns: ['Customer_ID', 'CLV', 'Churn']

       count
Churn
1       2989
0       2292

## Interpretation checklist

- Confirm the expected customer identifier and target columns.
- Check for unexpected missing values and duplicate customer rows.
- Ensure identifiers and target labels are not accidentally used as predictive features.
- Confirm that the feature columns match the saved model's expected inputs before deployment.

This notebook is a review aid; it does not certify that the full dataset is valid based on a sample alone.